__title__ = 'velero-bot-sdk'
__description__ = 'The library is designed to simplify the use of DSS contracts'
__version__ = '0.62.3'
__author__ = 'velerofinance'
__author_email__ = 'imdipperpines3199@gmail.com'